services:
  frontend:
    image: susguzman/f3-frontend:0.1.0-alpine
    ports:
      - 8888:80
  backend:
    image: susguzman/f3-backend:0.1.0
    ports:
      - 3800:3800
    env_file:
      - ./backend/.env
    restart: always
  mibasededatos:
    image: gvenzl/oracle-xe:21.3.0
    ports:
      - 1521:1521
    env_file:
      - ./database/.env
    volumes:
      - ./database:/container-entrypoint-initdb.d
      - oradata:/opt/oracle/oradata
volumes:
  oradata:
